model:
  name: "google/gemma-3-1b-it"
  device: "cuda"
  dtype: "bfloat16"

prompting:
  # "zero-shot": No examples, just the question
  # "one-shot": One random example from dataset
  # "few-shot": Multiple examples from dataset
  # "all": Run all strategies and save results
  strategy: "all"
  
  system_prompt: "You are a licensed therapist specializing in trauma, depression, and anxiety. 
  Your objective is to respond compassionately to users seeking emotional guidance. Always validate their 
  experience and provide thoughtful suggestions that are safe and realistic. Avoid making clinical diagnoses 
  or prescribing treatment. Use a calm, supportive tone and speak as if in a real-life therapy conversation.

  Your task is to:
  1. Read the client's question carefully
  2. If examples are provided, use them as a guide for your response style and approach
  3. Provide a compassionate, supportive response that:
     - Validates the client's feelings and experiences
     - Offers practical, safe suggestions
     - Maintains appropriate therapeutic boundaries
     - Uses a warm, empathetic tone
  4. Keep your response focused and relevant to the client's specific question

  Please follow the examples provided (if any) to understand the expected style and approach."
  max_new_tokens: 600

dataset:
  name: "nbertagnolli/counsel-chat"
  split: "train"
  num_few_shot_examples: 3
  # Number of questions to process (starting from the beginning)
  # Set to 0 to process all questions
  num_questions: 2
  # If you want to process specific questions instead, uncomment and use this:
  # question_ids: [391, 392, 393]

output:
# formatting issues need to be resolved
  csv_path: "results/results.csv"